# See all available PotionType names here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html

# List of potions that cannot be brewed
disabled-brewing:
  - HARMING
  - STRONG_HARMING

# List of potions that cannot be used
disabled-using:
  - HEALING
  - STRONG_HEALING

# List of potions that cannot be brewed or used
disabled-both:
  - POISON
  - STRONG_POISON
